sudo: required
services:
  - docker

before_install:
  - docker image build -t dime2lo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker container run -e CI=true dime2lo/react-test npm run test -- --coverage

after_success:
  - docker image build -t dime2lo/u-multi-client ./client
  - docker image build -t dime2lo/u-multi-nginx ./nginx
  - docker image build -t dime2lo/u-multi-server ./server
  - docker image build -t dime2lo/u-multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker image push dime2lo/u-multi-client
  - docker image push dime2lo/u-multi-nginx
  - docker image push dime2lo/u-multi-server
  - docker image push dime2lo/u-multi-worker